CREATE DATABASE EXERCICIO1_DML;
USE EXERCICIO1_DML;

CREATE TABLE IF NOT EXISTS PARTICIPANTES(
NUM_INSCRICAO INT,
CPF VARCHAR(14),
PRIMARY KEY(NUM_INSCRICAO,CPF),
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMPRESA VARCHAR(100));

 FORNECEDOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    PAIS_ORIGEM VARCHAR(50) NOT NULL,
    PESSOA_CONTATO VARCHAR(100),
    TELEFONE VARCHAR(20),
    HISTORICO_FORNECIMENTO TEXT
    );
