CREATE DATABASE EXERCICIO2_DML;
USE EXERCICIO2_DML;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    ID_PASSAGEIRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    ID_AEROPORTO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_AEROPORTO VARCHAR(10) NOT NULL,
    NOME_AEROPORTO VARCHAR(100) NOT NULL,
    LOCALIZACAO VARCHAR(255)
);
