CREATE DATABASE EXERCICIO2_DML;
USE EXERCICIO2_DML;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    ID_PASSAGEIRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

