CREATE DATABASE EXERCICIO5_DML;
USE EXERCICIO5_DML;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    STATUS_FIDELIDADE ENUM('ATIVO', 'INATIVO') NOT NULL
);

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CONTATO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100)
);

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100),
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

CREATE TABLE VENDAS (
    ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_VENDA DATETIME NOT NULL,
    FORMA_PAGAMENTO ENUM('CARTÃO', 'DINHEIRO', 'TRANSFERÊNCIA') NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE VENDAS_PRODUTOS (
    ID_VENDA INT,
    ID_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID_VENDA, ID_PRODUTO),
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT,
    DATA_PAGAMENTO DATETIME NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA)
);
