CREATE DATABASE EXERCICIO1_DML;
USE EXERCICIO1_DML;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNECEDOR_ID INT,
NOME_EMPRESA VARCHAR(100),
PRIMARY KEY(FORNECEDOR_ID),
ENDERECO VARCHAR(255) NOT NULL,
PAIS_ORIGEM VARCHAR(50) NOT NULL,
PESSOA_CONTATO VARCHAR(100),
TELEFONE VARCHAR(20));

CREATE TABLE IF NOT EXISTS PRODUTOS(
 PRODUTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    ESPECIFICACOES_TECNICAS TEXT,
    UNIDADE_MEDIDA VARCHAR(20),
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL));

CREATE TABLE IF NOT EXISTS ESTOQUE (
 ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
   PRODUTO_ID INT,
   QUANTIDADE_ATUAL INT NOT NULL,
   LOCALIZACAO VARCHAR(100),
   PONTO_RESSUPRIMENTO INT NOT NULL,
   CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID) 
    );

CREATE TABLE IF NOT EXISTS PEDIDOSCOMPRA (
PEDIDO_ID INT AUTO_INCREMENT PRIMARY KEY,
    FORNECEDOR_ID INT,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA_ESPERADA DATE,
    STATUS ENUM('EM PROCESSAMENTO ', 'ENVIADO', 'RECEBIDO', 'CANCELADO') NOT NULL,
    CONSTRAINT FK_PEDIDO FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID)
    );

CREATE TABLE IF NOT EXISTS ITENSPEDIDOCOMPRA (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE_SOLICITADA INT NOT NULL,
    CONSTRAINT FK_ITENS FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOSCOMPRA(PEDIDO_ID)
    CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID) 
    );

CREATE TABLE IF NOT EXISTS RECEBIMENTOMATERIAIS (
    RECEBIMENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT,
    DATA_RECEBIMENTO DATE NOT NULL,
    QUANTIDADE_RECEBIDA INT NOT NULL,
    CONDICAO ENUM('ACEITO', 'REJEITADO') NOT NULL,
    MOTIVO_REJEICAO TEXT,
    CONSTRAINT FK_MATERIAIS FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOSCOMPRA(PEDIDO_ID)
    );

CREATE TABLE IF NOT EXISTS FILIAIS (
    FILIAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CAPACIDADE_ARMAZENAMENTO INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS TRANSFERENCIAS (
    transferencia_id INT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_ID INT,
    FILIAL_ID INT,
    QUANTIDADE_TRANSFERIDA INT NOT NULL,
    DATA_TRANSFERIDA DATE NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES Produtos(PRODUTO_ID),
    CONSTRAINT FK_FILIAL FOREIGN KEY (FILIAL_ID) REFERENCES FILIAIS(FILIAL_ID));

INSERT INTO Fornecedores (nome_empresa, endereco, pais_origem, pessoa_contato, telefone, historico_fornecimento)
VALUES ('Fornecedor A', 'Rua A, 123', 'Brasil', 'João Silva', '(11) 1234-5678', '2023-10-01, 500');

INSERT INTO Fornecedores (nome_empresa, endereco, pais_origem, pessoa_contato, telefone, historico_fornecimento)
VALUES ('Fornecedor B', 'Avenida B, 456', 'China', 'Li Wei', '(21) 2345-6789', '2023-09-15, 200');

INSERT INTO Fornecedores (nome_empresa, endereco, pais_origem, pessoa_contato, telefone, historico_fornecimento)
VALUES ('Fornecedor C', 'Rua C, 789', 'EUA', 'John Doe', '(41) 3456-7890', '2023-08-01, 300');

INSERT INTO Fornecedores (nome_empresa, endereco, pais_origem, pessoa_contato, telefone, historico_fornecimento)
VALUES ('Fornecedor D', 'Estrada D, 101', 'Alemanha', 'Klaus Schmidt', '(51) 4567-8901', '2023-10-10, 100');

INSERT INTO Fornecedores (nome_empresa, endereco, pais_origem, pessoa_contato, telefone, historico_fornecimento)
VALUES ('Fornecedor E', 'Avenida E, 202', 'Japão', 'Yuki Tanaka', '(61) 5678-9012', '2023-07-20, 400');

INSERT INTO Pedidos_de_Compra (id_fornecedor, data_pedido, data_esperada_entrega, status_pedido)
VALUES (1, '2024-10-01', '2024-10-10', 'em processamento');

INSERT INTO Pedidos_de_Compra (id_fornecedor, data_pedido, data_esperada_entrega, status_pedido)
VALUES (2, '2024-09-15', '2024-09-25', 'enviado');

INSERT INTO Pedidos_de_Compra (id_fornecedor, data_pedido, data_esperada_entrega, status_pedido)
VALUES (3, '2024-08-01', '2024-08-15', 'recebido');

INSERT INTO Pedidos_de_Compra (id_fornecedor, data_pedido, data_esperada_entrega, status_pedido)
VALUES (4, '2024-10-10', '2024-10-20', 'em processamento');

INSERT INTO Pedidos_de_Compra (id_fornecedor, data_pedido, data_esperada_entrega, status_pedido)
VALUES (5, '2024-07-20', '2024-07-30', 'cancelado');

INSERT INTO Recebimento_de_Materiais (id_pedido, data_recebimento, quantidade_recebida, condicao_material)
VALUES (1, '2024-10-05', 100, 'aceito');
