CREATE SCHEMA EXERCICIO4;
USE EXERCICIO4;

CREATE TABLE ALUNOS (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE INSTRUTORES (
    ID_INSTRUTOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE MODALIDADES (
    ID_MODALIDADE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE PLANOS_TREINO (
    ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    DESCRICAO TEXT,
    DATA_ULTIMA_ATUALIZACAO DATE,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE AULAS (
    ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_MODALIDADE INT NOT NULL,
    ID_INSTRUTOR INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    CAPACIDADE INT NOT NULL,
    FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
    FOREIGN KEY (ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE MATRICULAS (
    ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    DATA_MATRICULA DATE NOT NULL,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE)
);

CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_MATRICULA INT NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
    FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULAS(ID_MATRICULA)
);
