CREATE SCHEMA EXERCICIO2;
USE EXERCICIO2;

CREATE TABLE PASSEJEIROS (
    PASSEJEIRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDERECO VARCHAR(255),
    HISTORICO_PASSEJEIROS TEXT
    );

CREATE TABLE AEROPORTOS (
    AEROPORTOS_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_AEROPORTO VARCHAR(10) UNIQUE NOT NULL,
    CIDADE TEXT,
    ESPECIFICACOES_DESTINO TEXT,
    PONTO_PARTIDA VARCHAR(100),
    PONTO_CHEGADA DECIMAL(10, 2) NOT NULL
    );

CREATE TABLE VOOS (
    VOO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORIGEM_VOO VARCHAR(10) UNIQUE NOT NULL,
    DESTINO TEXT,
    ESPECIFICACOES_DESTINO TEXT,
    HORARIO_PARTIDA VARCHAR(20),
    HORARIO_CHEGADA DECIMAL(10, 2) NOT NULL
    FOREIGN KEY (ORIGEM) REFERENCES AEROPORTOS(ID_AEROPORTO)
    FOREIGN KEY (DESTINO) REFERENCES AEROPORTOS(ID_AEROPORTO)
    );

CREATE TABLE AERONAVES (
    AERONAVE_ID INT AUTO_INCREMENT PRIMARY KEY,
    MODELO_AERONAVE VARCHAR(50) NOT NULL,
    NUMERO_REGISTRO VARCHAR(20) NOT NULL,
    HISTORICO_AERONAVES TEXT
    );


PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
