CREATE SCHEMA EXERCICIO1;
USE EXERCICIO1;

CREATE TABLE FORNECEDORES (
    FORNECEDOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    PAIS_ORIGEM VARCHAR(50) NOT NULL,
    PESSOA_CONTATO VARCHAR(100),
    TELEFONE VARCHAR(20),
    HISTORICO_FORNECIMENTO TEXT
);

CREATE TABLE PRODUTOS (
    PRODUTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    ESPECIFICACOES_TECNICAS TEXT,
    UNIDADE_MEDIDA VARCHAR(20),
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_ID INT,
    QUANTIDADE_ATUAL INT NOT NULL,
    LOCALIZACAO VARCHAR(100),
    PONTO_RESSUPRIMENTO INT NOT NULL,
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID) ON DELETE CASCADE
);

CREATE TABLE PEDIDOSCOMPRA (
    PEDIDO_ID INT AUTO_INCREMENT PRIMARY KEY,
    FORNECEDOR_ID INT,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA_ESPERADA DATE,
    STATUS ENUM('EM PROCESSAMENTO ', 'ENVIADO', 'RECEBIDO', 'CANCELADO') NOT NULL,
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES(FORNECEDOR_ID) ON DELETE CASCADE
);

CREATE TABLE ITENSPEDIDOCOMPRA (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT,
    PRODUTO_ID INT,
    QUANTIDADE_SOLICITADA INT NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOSCOMPRA(PEDIDO_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID) ON DELETE CASCADE
);

CREATE TABLE RECEBIMENTOMATERIAIS (
    RECEBIMENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID INT,
    DATA_RECEBIMENTO DATE NOT NULL,
    QUANTIDADE_RECEBIDA INT NOT NULL,
    CONDICAO ENUM('ACEITO', 'REJEITADO') NOT NULL,
    MOTIVO_REJEICAO TEXT,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOSCOMPRA(PEDIDO_ID) ON DELETE CASCADE
);

CREATE TABLE FILIAIS (
    FILIAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CAPACIDADE_ARMAZENAMENTO INT NOT NULL
);

CREATE TABLE TRANSFERENCIAS (
    transferencia_id INT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_ID INT,
    FILIAL_ID INT,
    QUANTIDADE_TRANSFERIDA INT NOT NULL,
    DATA_TRANSFERIDA DATE NOT NULL,
    FOREIGN KEY (PRODUTO_ID) REFERENCES Produtos(produto_id) ON DELETE CASCADE,
    FOREIGN KEY (FILIAL_ID) REFERENCES FILIAIS(FILIAL_ID) ON DELETE CASCADE
);
