CREATE SCHEMA EXERCICIO2;
USE EXERCICIO2;

CREATE TABLE PASSAGEIROS (
    ID_PASSAGEIRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255)
);

CREATE TABLE AEROPORTOS (
    ID_AEROPORTO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_AEROPORTO VARCHAR(10) NOT NULL UNIQUE,
    NOME_AEROPORTO VARCHAR(100) NOT NULL,
    LOCALIZACAO VARCHAR(255)
);

CREATE TABLE AERONAVES (
    ID_AERONAVE INT AUTO_INCREMENT PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    IDENTIFICADOR VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE VOOS (
    ID_VOO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_VOO VARCHAR(10) NOT NULL UNIQUE,
    ORIGEM INT,
    DESTINO INT,
    HORARIO_PARTIDA DATETIME NOT NULL,
    HORARIO_CHEGADA DATETIME NOT NULL,
    FOREIGN KEY (ORIGEM) REFERENCES AEROPORTOS(ID_AEROPORTO),
    FOREIGN KEY (DESTINO) REFERENCES AEROPORTOS(ID_AEROPORTO)
);

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    CARGO ENUM('PILOTO', 'COMISSARIO', 'EQUIPE_DE_SOLO') NOT NULL
);

CREATE TABLE RESERVAS (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PASSAGEIRO INT,
    ID_VOO INT,
    DATA_RESERVA DATETIME NOT NULL,
    FOREIGN KEY (ID_PASSAGEIRO) REFERENCES PASSAGEIROS(ID_PASSAGEIRO),
    FOREIGN KEY (ID_VOO) REFERENCES VOOS(ID_VOO)
);

CREATE TABLE OPERACOES_VOO (
    ID_OPERACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_VOO INT,
    ID_FUNCIONARIO INT,
    DATA_OPERACAO DATETIME NOT NULL,
    FOREIGN KEY (ID_VOO) REFERENCES VOOS(ID_VOO),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);
